--  write a  SQL query to select all the salespeople. Return salesman_id, name, city, commission with the percent sign (%).
SELECT 
    salesman_id, 
    name, 
    city, 
    CONCAT(commission * 100, '%') AS commission
FROM 
    salesman;
-- write a SQL query to find the number of orders booked for each day. Return the result in a format like "For 2001-10-10 there are 15 orders".". Sample table: orders

SELECT 
    CONCAT('For ', ord_date, ' there are ', COUNT(ord_no), ' orders') AS order_summary
FROM 
    orders
GROUP BY 
    ord_date;

-- write a SQL query that calculates the maximum purchase amount generated by each salesperson for each order date. Sort the result-set by salesperson id and order date in ascending order. 
-- Return salesperson id, order date and maximum purchase amount. Sample table: orders

SELECT 
    salesman_id, 
    ord_date, 
    MAX(purch_amt) AS max_purchase_amount
FROM 
    orders
GROUP BY 
    salesman_id, ord_date
ORDER BY 
    salesman_id ASC, ord_date ASC;

salesman_id	ord_date	max_purchase_amount
5001	      2012-04-25	3045.60
5001	      2012-07-27	2400.60
5001	      2012-09-10	5760.00
5001	      2012-10-05	65.26
5002	      2012-06-27	250.45
5002	      2012-09-10	948.50
5002	      2012-10-05	150.50
5003	      2012-08-17	110.50
5003	      2012-10-10	2480.40
5005	      2012-09-10	270.65
5006	      2012-10-10	1983.43
5007	      2012-08-17	75.29

-- -- This query selects specific columns ('cust_name', 'city', 'grade') from the 'customer' table.
-- It orders the result set by the third column ('grade') in descending order using the column index.
SELECT cust_name, city, grade
-- Specifies the table from which to retrieve the data (in this case, 'customer').
FROM customer
-- Orders the result set by the third column ('grade') in descending order using the column index (3).
ORDER BY 3 DESC;

-- From the following table, write a SQL query that counts the unique orders and the highest purchase amount for each customer. 
-- Sort the result-set in descending order on 2nd field. Return customer ID, number of distinct orders and highest purchase amount by each customer. Sample table: orders

SELECT customer_id, COUNT(DISTINCT ord_no), MAX(purch_amt)
from orders
GROUP BY customer_id
ORDER BY 2 DESC;

-- write a  SQL query to calculate the summation of purchase amount, total commission (15% for all salespeople) by each order date. Sort the result-set on order date.
-- Return order date, summation of purchase amount and commission.

SELECT ord_date, SUM(purch_amt), SUM(purch_amt)*0.15  AS commission
from orders
GROUP BY 
ord_date
ORDER BY 1 ;
