https://www.w3resource.com/sql-exercises/subqueries/index.php

-- 1. write a  SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
--  USING subquery
SELECT *
FROM orders o 
WHERE salesman_id IN
  (SELECT salesman_id From salesman 
   where name = 'Paul Adam');
-- USING JOIN
SELECT *
FROM orders o 
Inner JOIN salesman s
ON o.salesman_id = s.salesman_id
WHERE s.name = 'Paul Adam';

--2.  write a SQL query to find all orders generated by London-based salespeople. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
SELECT * FROM orders  
WHERE salesman_id IN  
   (select salesman_id from salesman where city = 'London'); 
-- you can solve it using join also but subquery is generally used to findvalues from one table to filter another table.

-- 3. a SQL query to find all orders generated by the salespeople who may work for customers whose id is 3007. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
--  it is saying may work  so o/p is
ord_no	purch_amt	ord_date	customer_id	salesman_id
70002	65.26		2012-10-05	3002		5001
70005	2400.60		2012-07-27	3007		5001
70008	5760.00		2012-09-10	3002		5001
70013	3045.60		2012-04-25	3002		5001
SELECT * FROM orders  
WHERE  salesman_id =  
   (select DISTINCT salesman_id 
    from orders 
    where customer_id = 3007);


-- 4. SQL query to find the order values greater than the average order value of 10th October 2012. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
SELECT * FROM orders  
WHERE purch_amt >  
   (select AVG(purch_amt) 
    from orders 
    where ord_date = '2012-10-10');

--6. From the following tables write a SQL query to determine the commission of the salespeople in Paris. Return commission.
SELECT commission FROM salesman  
WHERE salesman_id =  
   (select salesman_id
    from customer 
    where city = 'Paris');

-- Write a query to display all the customers whose ID is 2001 below the salesperson ID of Mc Lyon.
SELECT * FROM customer  
WHERE  customer_id =  
   (select salesman_id - 2001
    from salesman 
    where name = 'Mc Lyon');
